#!/bin/bash
time=`date +"%m_%d_%Y"`
exec 2>&1 > /tmp/bootstrap_$time

# change hostname
sudo hostname puppet.mycloudchoice.com
sudo echo '127.0.1.3 puppet.mycloudchoice.com puppetmaster puppet' >> /etc/hosts
cat << EOF > /etc/hostname
puppet.mycloudchoice.com
EOF

sudo apt-get update
sudo apt-get install --yes puppetmaster
 
sudo rm /var/lib/puppet/ssl/ca/inventory.txt
if [ $? != 0 ]; then
    echo " rm inventory.txt failed."
fi

# run puppet master; not working need site.pp
#puppet apply

# does not work with puppet 3.3
# sudo apt-get install puppetmaster-common
sudo puppet cert list 
if [ $? != 0 ]; then
    echo " puppet cert list failed."
fi

sudo puppet cert sign 
if [ $? != 0 ]; then
    echo " puppet cert sign all  failed."
fi

# salt
sudo mkdir /srv/salt
echo '127.0.1.2 salt.mycloudchoice.com' >> /etc/hosts
sudo apt-get update
sudo apt-get install --yes salt-master

